export const metrics = [
  ["sessions", "Completed sessions", "number", "Practice"],
  ["capacity", "Session capacity", "number", "Practice"],
  ["utilization", "Clinician utilization", "percent", "Practice"],
  ["unservedSessions", "Unserved demand", "number", "Practice"],
  ["roomCapacity", "Room capacity", "number", "Capacity"],
  ["roomUtilization", "Room utilization", "percent", "Capacity"],
  ["requiredRooms", "Rooms required", "number", "Capacity"],
  ["leads", "Leads", "number", "Growth"],
  ["clients", "New clients", "number", "Growth"],
  ["consultations", "Consultations", "number", "Growth"],
  ["revenue", "Earned revenue", "currency", "Finances"],
  ["collections", "Cash collections", "currency", "Finances"],
  ["clinicianPay", "Clinician compensation", "currency", "Finances"],
  ["employerBurden", "Employer burden", "currency", "Finances"],
  ["staffCost", "Support staff cost", "currency", "Finances"],
  ["overhead", "Operating overhead", "currency", "Finances"],
  ["marketing", "Marketing costs", "currency", "Growth"],
  ["adSpend", "Advertising spend", "currency", "Growth"],
  ["cpl", "Cost per lead", "currency", "Growth"],
  ["consultationPct", "Lead-to-consultation rate", "percent", "Growth"],
  ["closePct", "Consultation close rate", "percent", "Growth"],
  ["attendance", "Session attendance", "percent", "Practice"],
  ["fees", "Payment fees", "currency", "Finances"],
  ["profit", "Operating profit after owner payroll", "currency", "Finances"],
  ["ownerPayroll", "Owner payroll", "currency", "Family"],
  ["ownerClinicalPay", "Owner clinical compensation", "currency", "Family"],
  ["taxReserve", "Tax allocation", "currency", "Cash"],
  ["reserves", "Reserve allocation", "currency", "Cash"],
  ["distributions", "Owner distributions", "currency", "Family"],
  ["retainedCash", "Available cash change", "currency", "Cash"],
  ["cash", "Available cash balance", "currency", "Cash"],
  ["familyTakeHome", "Family pay from practice", "currency", "Family"],
  ["breakEvenSessions", "Break-even sessions", "number", "Finances"],
  ["cac", "Acquisition cost", "currency", "Growth"],
  ["ltv", "Revenue lifetime value", "currency", "Growth"],
  ["roas", "Revenue ROAS", "number", "Growth"],
  ["contributionRoas", "Contribution ROAS", "number", "Growth"],
  ["netRoi", "Net marketing ROI", "percent", "Growth"],
  ["runway", "Cash runway in months", "number", "Cash"],
] as const;
export const metricMap = Object.fromEntries(
  metrics.map(([key, label, unit, group]) => [
    key,
    { key, label, unit, group },
  ]),
);
