const colors = {
  light: {
    text: "#0f172a",
    tint: "#16a08a",
    background: "#f9fbfd",
    foreground: "#0f172a",
    card: "#ffffff",
    cardForeground: "#0f172a",
    primary: "#1e3a5f",
    primaryForeground: "#f8fafc",
    secondary: "#16a08a",
    secondaryForeground: "#f8fafc",
    muted: "#f1f5f9",
    mutedForeground: "#64748b",
    accent: "#edfaf8",
    accentForeground: "#0c7a6b",
    destructive: "#ef4444",
    destructiveForeground: "#f8fafc",
    border: "#e2e8f0",
    input: "#e2e8f0",
  },
  dark: {
    text: "#f8fafc",
    tint: "#1abda6",
    background: "#0f172a",
    foreground: "#f8fafc",
    card: "#111d2e",
    cardForeground: "#f8fafc",
    primary: "#e2eaf4",
    primaryForeground: "#0f172a",
    secondary: "#1abda6",
    secondaryForeground: "#0f172a",
    muted: "#162a40",
    mutedForeground: "#94a3b8",
    accent: "#09584e",
    accentForeground: "#edfaf8",
    destructive: "#7f1d1d",
    destructiveForeground: "#f8fafc",
    border: "#1e3a5f",
    input: "#1e3a5f",
  },
  radius: 6,
};

export default colors;
